### ISSUE TITLE
text-blend-order style error

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#106]
https://github.com/tangrams/tron/blob/gh-pages/layers/buildings-labels.yaml#L68
![screen shot 2016-09-14 at 2 23 20 pm 2](https://cloud.githubusercontent.com/assets/346914/18524545/d0b31c76-7a86-11e6-95fc-419640f9c554.png)

**Comment by patriciogonzalezvivo** [comment]
Should be just `text`... right?

**Comment by sensescape** [comment]
yes, thanks @patriciogonzalezvivo  for catching! just fixed it
