### ISSUE TITLE
Less shimmery water

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#107]
I [stepped the zoom transition](https://github.com/tangrams/tron/commit/9ada6fe3d07444b4f6c483c8a07bac7498fb3799) on what seams the most efficient why to make the water shimmering zoom transition less  uncomfortable in this PR https://github.com/tangrams/tron/commit/9ada6fe3d07444b4f6c483c8a07bac7498fb3799

@sensescape feel free to adapt the scale of the shimmering triangular pattern with this two `defines` values (`SHIMMERING_ZOOM_IN` and `SHIMMERING_ZOOM_OUT`) [here](https://github.com/tangrams/tron/blob/gh-pages/styles/polygons.yaml#L43-L44)
![00](https://cloud.githubusercontent.com/assets/346914/18527844/66a04594-7a94-11e6-8697-829326a98d0b.gif)

**Comment by sensescape** [comment]
ok. thanks! @patriciogonzalezvivo
