### ISSUE TITLE
Replace `polygons-stripes` by `polygons-diagonal-stripes`

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#12]
Hi @sensescape, we should change this filtered layers https://github.com/tangrams/tron/blob/gh-pages/layers/landuse.yaml#L229-L261 to use `polygons-diagonal-stripes`.

I notice that the difference between them is the angle... which will not make it for production because rotating patterns is costly... that's way I'm suggesting `polygons-diagonal-stripes` BUT that said... we can add something to `polygons-diagonal-stripes` to flip horizontally the diagonal stripe pattern. How that sounds?

Also we may use other patterns here? like diagonal grid?? dots? 
I can come up with a version for each one that modulate the size depending the normal map? maybe? what are your thoughts?

**Comment by sensescape** [comment]
Sure, I can switch to polygons-diagonal-stripes for now. Yes, let's try new patterns! Open to suggestions. We could try dots. (I was reserving grids for man-made areas) Let's use the elevation type patterns for nature areas. Also we could try the contour one you sent, this one:
<img width="512" alt="screen_shot_2016-07-15_at_4 33 03_pm_1024" src="https://cloud.githubusercontent.com/assets/466585/17007496/2ab5ddd6-4e9e-11e6-8fdd-c7f1b2555f7f.png">

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F70cd74d3406876f3e0cf93d8afffd45d%2Fraw%2Fdc95ebbc8c75c2cdd45f27fb9733c738881b2604%2Fscene.yaml#12.293063082015689/37.5457/-122.4307

**Comment by patriciogonzalezvivo** [comment]
Hi! I add to patterns to play `elevation-contours` and `elevation-color-contours` (which then I modify to use our tron palette... to make different colors... you can modify it bay changing the CONTROUR_RANGE)

https://github.com/tangrams/tron/commit/9775877fda9574da64278d60338d1b6c1555e835
https://github.com/tangrams/tron/commit/694f928658a2316130842c00854a5726339a403b

![screen shot 2016-07-21 at 10 39 41 am](https://cloud.githubusercontent.com/assets/346914/17026842/7f6c720e-4f2f-11e6-8e8e-859177fac386.png)
![screen shot 2016-07-21 at 10 32 52 am](https://cloud.githubusercontent.com/assets/346914/17026843/7f6cabd4-4f2f-11e6-9bfc-3a4d6921b6e8.png)

**Comment by nvkelso** [comment]
Wow!

**Comment by nvkelso** [comment]
Completed / out-dated. Closing.
