### ISSUE TITLE
Add zip package option

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#121]
Compress all the relevant src files into a single ZIP.

**Comment by nvkelso** [comment]
Work in progress:
- https://github.com/tangrams/tron/commit/b5df8970ca00901e22b01a9eae427f33a64654f6
- https://github.com/tangrams/tron/commit/42c12440269afb70203e0bd10013a6dfdf4c25dd

**Comment by patriciogonzalezvivo** [comment]
The zip script is ready... should I add the `.zip` file to the repo? or are we using releases?

**Comment by tallytalwar** [comment]
ES does not support zip yet!

**Comment by patriciogonzalezvivo** [comment]
@tallytalwar but it will : P

**Comment by nvkelso** [comment]
@patriciogonzalezvivo The .zip files should not be added to the repo, the bundle step should only post those to the CDN during a release.

**Comment by patriciogonzalezvivo** [comment]
@nvkelso I made the bundler a separate tools so we can refine it during time, and consistently apply to all future styles. https://github.com/tangrams/bundler

**Comment by patriciogonzalezvivo** [comment]
can we close this one?

**Comment by nvkelso** [comment]
Yes
