### ISSUE TITLE
building proposal

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#13]
Lines 
![screen shot 2016-07-20 at 3 32 20 pm](https://cloud.githubusercontent.com/assets/346914/17000634/5f068c00-4e91-11e6-8391-686566dbe4bf.png)

random pattern in gradiant
![screen shot 2016-07-20 at 3 47 44 pm](https://cloud.githubusercontent.com/assets/346914/17000639/62a8e178-4e91-11e6-83f8-8eac696d2e2d.png)

**Comment by sensescape** [comment]
i love this! is the above what we have now? but with random colors? The above looks so good too.

Can we see the pixels come in sooner, around z18? Right now I don't see them until z20.
z18 now:
<img width="1229" alt="screen shot 2016-07-20 at 5 15 37 pm" src="https://cloud.githubusercontent.com/assets/466585/17007441/a9c27c5c-4e9d-11e6-86f2-952022c560b8.png">

**Comment by patriciogonzalezvivo** [comment]
Sure! Yesterday I was working on a generalize zoom interpolation module. http://tangrams.github.io/blocks/#functions-zoom

How it works?
Well, you add it like any other block, by `import`ing it and then `mix`ing it to the style.

Then you set the zooms wher should **start** and **end** the interpolation, setting the `defines`: `ZOOM_START` and `ZOOM_END`.
Then you use the `zoom()` function... by default this function gives a number between 0 and 1. But you can change it to interpolate any thing (`floats`, `vec2`, `vec3`, `vec4` and even other functions). For that you Just need to change de `defines`: `ZOOM_IN`, and `ZOOM_OUT`.

Another thing that can be change is the type of interpolation, de default is `linear`, but can be any of the [easing functions TangramBlocks](http://tangrams.github.io/blocks/#functions-easing). For it you need to change the`define` of this block like this: `ZOOM: quadraticInOut`

https://github.com/tangrams/tron/blob/gh-pages/layers/buildings.yaml#L56-L57

**Comment by patriciogonzalezvivo** [comment]
How about this?
![screen shot 2016-07-21 at 9 45 50 am](https://cloud.githubusercontent.com/assets/346914/17025001/f724fde6-4f27-11e6-9f2f-95947be52c83.png)
![screen shot 2016-07-21 at 9 45 59 am](https://cloud.githubusercontent.com/assets/346914/17025002/f73e5250-4f27-11e6-8445-d603a8740d72.png)
