### ISSUE TITLE
android

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tron-style#131]
won't your style work with android tangram-es?

**Comment by nvkelso** [comment]
It should, but you probably need to use the Mapzen CDN version, or make
sure you do a git checkout of this repo, and init & update  all submodules
to fetch the required blocks components.

**Comment by ivangorelow** [comment]
what is mapzen cdn?

**Comment by ivangorelow** [comment]
I've downloaded  blocks, and map works, but i don't have ani effects

**Comment by nvkelso** [comment]
See https://mapzen.com/documentation/cartography/styles/:
- https://mapzen.com/carto/tron-style/2/tron-style.zip
  -
  https://mapzen.com/carto/tron-style-more-labels/2/tron-style-more-labels.zip
  -
  https://mapzen.com/carto/tron-style-no-labels/2/tron-style-no-labels.zip
