### ISSUE TITLE
highway glow - go back to soft edge

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#14]
Hi! @patriciogonzalezvivo 

Could we go back to the softer edge for the glow lines? Here's a comparison:

Before:
<img width="745" alt="screen shot 2016-07-18 at 11 46 42 am" src="https://cloud.githubusercontent.com/assets/466585/17006566/ad5475e8-4e96-11e6-8b14-a136e4dc43ca.png">

Current, harder edge:
<img width="1005" alt="screen shot 2016-07-20 at 4 26 31 pm" src="https://cloud.githubusercontent.com/assets/466585/17006575/bde19fa8-4e96-11e6-99ed-ccbbe95c7c0b.png">

**Comment by patriciogonzalezvivo** [comment]
I will look into it

**Comment by patriciogonzalezvivo** [comment]
How about this?
![screen shot 2016-07-21 at 9 45 50 am](https://cloud.githubusercontent.com/assets/346914/17025038/12ea855a-4f28-11e6-813f-7877e196c2f3.png)
![screen shot 2016-07-21 at 9 45 59 am](https://cloud.githubusercontent.com/assets/346914/17025037/12dfd894-4f28-11e6-913d-9db6994100b6.png)

**Comment by patriciogonzalezvivo** [comment]
https://github.com/tangrams/tron/commit/dd2e9672e72efb3bc6a812eb9f826301f98e8e46

**Comment by sensescape** [comment]
yes!
