### ISSUE TITLE
landuse elevation stripes

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#15]
Hi! @patriciogonzalezvivo 

I miss the detail from the finer lines version of elevation-stripes:
<img width="1003" alt="screen shot 2016-07-18 at 11 34 05 am" src="https://cloud.githubusercontent.com/assets/466585/17007063/8557f232-4e9a-11e6-9b7d-8e361d96245d.png">

Now, with thicker line width:
<img width="1003" alt="screen shot 2016-07-20 at 4 55 05 pm" src="https://cloud.githubusercontent.com/assets/466585/17007094/c57608d6-4e9a-11e6-99d4-987797abc1b9.png">

I think I'll need your help adjusting the line widths. Was tweaking them but couldn't get the result I wanted:
https://github.com/tangrams/tron/blob/gh-pages/layers/landuse.yaml#L224-L227

**Comment by sensescape** [comment]
Here's another example, Hawaii:
Before:
<img width="1382" alt="screen shot 2016-07-14 at 4 30 45 pm" src="https://cloud.githubusercontent.com/assets/466585/17007383/1cc7502a-4e9d-11e6-881b-d8bcbda3cde7.png">
Now:
<img width="1229" alt="screen shot 2016-07-20 at 5 12 24 pm" src="https://cloud.githubusercontent.com/assets/466585/17007395/3096d558-4e9d-11e6-8881-abcdca2a4473.png">

**Comment by patriciogonzalezvivo** [comment]
Sorry for that, I made preaty intense changes to make that function more efficient... the `STRIPES_SCALE` need to be adjusted here https://github.com/tangrams/tron/blob/gh-pages/layers/landuse.yaml#L222 try turning the number up to something that makes more sense

**Comment by patriciogonzalezvivo** [comment]
How about there? https://github.com/tangrams/tron/commit/a65e39ee28e997a78f31151762d1d37455829424

![screen shot 2016-07-21 at 9 51 22 am](https://cloud.githubusercontent.com/assets/346914/17025198/dcc50292-4f28-11e6-8f11-ce4a1b4fda48.png)

**Comment by sensescape** [comment]
nice!
