### ISSUE TITLE
What do you think about this earth/roads transition? 

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#16]
@sensescape  There was a gap between the earth stripes disappear and roads apear between z5 and z6 that was bothering me... the earth use to appear to flat and in the flow feels like a bump.

So I change this things https://github.com/tangrams/tron/commit/e2345d92650bd57e3c9eff0a8dfe6b8c73fa2394

The early eart stripes animation goes a little longer and over lap with a new fade animation on the roads, lightening up ( using the new `zoom()` function from the block [functions-zoom](http://tangrams.github.io/blocks/#functions-zoom) )

And now looks like this
![2016-07-21 11_11_16](https://cloud.githubusercontent.com/assets/346914/17027943/ef1214fc-4f33-11e6-9544-48debb2c308f.gif)

What do you think?

**Comment by sensescape** [comment]
looks good!
