### ISSUE TITLE
Tron no-animation version

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#17]
Hi! @patriciogonzalezvivo 

@nvkelso started no-animation version of tron, not working yet, but will need your help to incorporate with the blocks. https://github.com/tangrams/tron/commit/e420c678c068c26e50f5abb01d1251d550d54090

Here's what we started:

From the top:
https://github.com/tangrams/tron/blob/e420c678c068c26e50f5abb01d1251d550d54090/tron.yaml#L16

https://github.com/tangrams/tron/blob/e420c678c068c26e50f5abb01d1251d550d54090/tron-no-animation.yaml#L5

To water:
https://github.com/tangrams/tron/blob/e420c678c068c26e50f5abb01d1251d550d54090/layers/water.yaml#L155-L160

for these water boundaries:
https://github.com/tangrams/tron/blob/e420c678c068c26e50f5abb01d1251d550d54090/layers/water.yaml#L61-L85

https://github.com/tangrams/tron/blob/e420c678c068c26e50f5abb01d1251d550d54090/styles/lines.yaml#L5-L27

**Comment by patriciogonzalezvivo** [comment]
Hi! I guess I don't understand why we have animated and not animated layers... when the only thing we need to change is the `animated` tag to false. Is because they change on zooming? right?

**Comment by sensescape** [comment]
This is done.
