### ISSUE TITLE
this is experimental, right?

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#18]
https://tangrams.github.io/tron/#14.785377687974684/40.8080/-74.8714

![screen shot 2016-07-25 at 11 05 09 am](https://cloud.githubusercontent.com/assets/346914/17106034/b4e2dbbe-5257-11e6-9b72-ebb433ed43b8.png)

**Comment by sensescape** [comment]
Hi! @patriciogonzalezvivo I've been so focused on roads, no haven't touched this yet. Have to figure out what to do here. Ohhh, we were going to add diagonal stripes here. But let's experiment some more with elevation patterns. What do you think?
