### ISSUE TITLE
dash lines and dot lines with glow

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#19]
Hi! @patriciogonzalezvivo 
I'm testing out adding more detail to major primary and secondary roads, can we try dots and regular dash lines with glow?

Here's my first test, detail starts to appear at z18 and up:
<img width="635" alt="screen shot 2016-07-26 at 4 03 03 pm" src="https://cloud.githubusercontent.com/assets/466585/17158424/176b946c-534b-11e6-9a93-82d0b9996739.png">

**Comment by nvkelso** [comment]
What do animated roads look like in this style? Longer moving lines that are tapered at one end (versus the shorter pills in v1?)

**Comment by sensescape** [comment]
But I thought direction is not accurate? Might be confusing

**Comment by patriciogonzalezvivo** [comment]
In tron and matrix trafic goes according what OSM said... I think

I was wishing to add something like this http://player.thebookofshaders.com/?log=160621170831

Or like this:

![368f454f8509ad0b520a4ba33a2bf13a](https://cloud.githubusercontent.com/assets/346914/17176220/a395a534-53d9-11e6-9482-10870bb517b1.gif)
![75ae39c682a4dad5ea527b1edbdd4ba4](https://cloud.githubusercontent.com/assets/346914/17176221/a398ae00-53d9-11e6-8fba-d667163069fb.gif)

**Comment by patriciogonzalezvivo** [comment]
![00](https://cloud.githubusercontent.com/assets/346914/17177230/7246dc82-53de-11e6-9357-710dc7b5ac92.gif)

http://player.thebookofshaders.com/?log=160727133140

; )

**Comment by patriciogonzalezvivo** [comment]
w color 
http://player.thebookofshaders.com/?log=160727134832

![01](https://cloud.githubusercontent.com/assets/346914/17177432/6204cbe4-53df-11e6-8bea-f0402ce3dac1.gif)

**Comment by sensescape** [comment]
Hesitant about adding movement to the roads, I find it distracting. Can we try both with movement and without and see? But all of these look great! But not sure about the yellow green orange color for roads

**Comment by sensescape** [comment]
@patriciogonzalezvivo center glow lines are here. testing it out starting at high zoom z17 for these road types:
https://github.com/tangrams/tron/blob/c1ec5736d81ad1974c1848388c3970fda63ad12e/layers/roads.yaml#L199-L207

https://github.com/tangrams/tron/blob/c1ec5736d81ad1974c1848388c3970fda63ad12e/layers/roads.yaml#L218-L226

https://github.com/tangrams/tron/blob/c1ec5736d81ad1974c1848388c3970fda63ad12e/layers/roads.yaml#L259-L267

**Comment by sensescape** [comment]
I love the motion of the red and white one.

**Comment by patriciogonzalezvivo** [comment]
@sensescape I think those are the glow light... under the road... right? the dashes should be on solid `lines` right?

**Comment by sensescape** [comment]
dashes go on the center-glow (center-line), not the highway-glow

**Comment by patriciogonzalezvivo** [comment]
![02](https://cloud.githubusercontent.com/assets/346914/17186159/0922cd1e-5402-11e6-9474-a99d3be29516.gif)
![00](https://cloud.githubusercontent.com/assets/346914/17186160/09251a92-5402-11e6-931d-57191c69c732.gif)

**Comment by patriciogonzalezvivo** [comment]
https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Ffdd723dafa33a486e0df5c6dd5950019%2Fraw%2F0a0ea1115099554b0502aeae9ed269ef7e13a41e%2Fscene.yaml#18.539890481703946/40.69941/-73.99102

**Comment by patriciogonzalezvivo** [comment]
Here is an example of the dashes w glow https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F30c5f75631796eba26631652360fd576%2Fraw%2Ff38f44bb1c00d65be5489712e0d41c35331423f8%2Fscene.yaml#22.05160006744323/40.69939/-73.99119

I think that the width of the roads needs to be bigger to appreciate the glow. Also the the dashes are on TOP of the cars... personally I think this dashes should be in the shader. Probably @bcamper will  argue that's expensive : )

**Comment by patriciogonzalezvivo** [comment]
I add a transition for the "cars" 

check the short version here:
https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F5da71c833cb4dbf559ea3420cd620f7f%2Fraw%2F5d457c416efbe6c58923c1bcc00dc83c4a28a6d7%2Fscene.yaml#17.74983181759487/40.70659/-74.00834

See the commit here: https://github.com/tangrams/tron/commit/7398ef4d9bea423f806b458983dd604062823fac
