### ISSUE TITLE
Transit

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#20]
@sensescape I have the feeling that we are over using the blue/greenish color... what if we use some of the other tron colors like bright orange or purple? maybe for transit?

**Comment by sensescape** [comment]
@patriciogonzalezvivo sure, i'll try both

**Comment by patriciogonzalezvivo** [comment]
: )

**Comment by sensescape** [comment]
Trying out this lavender today:
<img width="1538" alt="screen shot 2016-07-27 at 2 32 23 pm" src="https://cloud.githubusercontent.com/assets/466585/17193452/e507c5dc-5407-11e6-9733-4e4ad79060b8.png">
<img width="1160" alt="screen shot 2016-07-27 at 2 37 26 pm" src="https://cloud.githubusercontent.com/assets/466585/17193467/fd005230-5407-11e6-8b4e-88088942bfe6.png">
<img width="1099" alt="screen shot 2016-07-27 at 2 35 55 pm" src="https://cloud.githubusercontent.com/assets/466585/17193472/0990a860-5408-11e6-87af-354cc856813a.png">

**Comment by patriciogonzalezvivo** [comment]
nice!

**Comment by patriciogonzalezvivo** [comment]
![af1b58b944c2d44f883a9d40058e722c](https://cloud.githubusercontent.com/assets/346914/17213912/7310b252-54a4-11e6-81ea-b09d3b7971af.jpg)
