### ISSUE TITLE
Choose fonts

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#21]
Will start adding labels soon

**Comment by patriciogonzalezvivo** [comment]
awesome!

**Comment by sensescape** [comment]
@patriciogonzalezvivo @bcamper @nvkelso 
Here are the first tests for country names, my favorites from Google fonts so far:

Audiowide:
<img width="869" alt="screen shot 2016-07-27 at 4 14 22 pm" src="https://cloud.githubusercontent.com/assets/466585/17195865/5a679ba6-5415-11e6-9c30-a064d82ba68b.png">

<img width="1300" alt="screen shot 2016-07-27 at 4 30 12 pm" src="https://cloud.githubusercontent.com/assets/466585/17196174/6fdcf290-5417-11e6-863a-b04ca66c9bcf.png">

Orbitron:
<img width="656" alt="screen shot 2016-07-27 at 4 16 07 pm" src="https://cloud.githubusercontent.com/assets/466585/17195892/774836ea-5415-11e6-89a1-aaa9326f37b1.png">

<img width="624" alt="screen shot 2016-07-27 at 4 32 07 pm" src="https://cloud.githubusercontent.com/assets/466585/17196203/b4c79b44-5417-11e6-8b51-cfd2d6cc6136.png">

**Comment by nvkelso** [comment]
Both are nice, I prefer **Audiowide**.

**Comment by patriciogonzalezvivo** [comment]
I like **Orbitron** : P

**Comment by sensescape** [comment]
haha, we can use both, I want to mix fonts on this map : )
