### ISSUE TITLE
Add more building dimension at mid zooms

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#23]
The v1 has some sort of polygon fill variation according to building height where taller / bigger buildings are darker fill. Right now v2 feels flat in comparison. 

See:
- https://tangrams.github.io/tangram-sandbox/tangram.html?styles/tron#16.14851779753645/37.78922/-122.39846

**Comment by patriciogonzalezvivo** [comment]
the trick is in by modulating the 'width' lines:

https://github.com/tangrams/tangram-sandbox/blob/gh-pages/styles/tron.yaml#L149-L170

**Comment by patriciogonzalezvivo** [comment]
The darker/brighter is a sub product of the super position of transparent geometries with `add` blending at tiles edges, or buildings that have other geometries inside : )
![screen shot 2016-07-27 at 2 50 46 pm](https://cloud.githubusercontent.com/assets/346914/17188162/f131664a-5409-11e6-8ca8-3e33702d22c5.png)

**Comment by patriciogonzalezvivo** [comment]
Adding dynamic width and height to the buildings according height (for the width) and zoom level (for the height) here https://github.com/tangrams/tron/commit/9a07be1644bfe21fb19959d62ff540eaeb92560d

![00](https://cloud.githubusercontent.com/assets/346914/17189488/a698c816-540f-11e6-912a-1c626afda0d0.gif)

**Comment by patriciogonzalezvivo** [comment]
Here are the blocks http://tangrams.github.io/blocks/#geometry-dynamic-height
http://tangrams.github.io/blocks/#geometry-dynamic-width

**Comment by nvkelso** [comment]
nice! is this also modifying the roof fill?

**Comment by patriciogonzalezvivo** [comment]
no... roof was no fill... because the blend mode is `add` I try to make buildings more invisible conform it goes up... other wise will happen what tron 1. and matrix... the buildings becomes bright spots... and the patterns become confusing.

This way seams that the pattern is some sort of semi translucent glass... so if you look directly to it (roofs) you see through... but the more from an angle (like the base) you see the semi translucent random pattern

**Comment by sensescape** [comment]
I created an issue in relation to this because I found the lines too thin and noisy. Also buildings are not so visible now in cities with shorter buildings.
https://github.com/tangrams/tron/issues/25

Is there another way to add more depth without losing solid lines from previous version?
