### ISSUE TITLE
Can we have the same shimmering animation here??

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#24]
![screen shot 2016-07-27 at 3 50 56 pm](https://cloud.githubusercontent.com/assets/346914/17189974/f81d6208-5411-11e6-89f8-749d4c16c275.png)

**Comment by sensescape** [comment]
yes! have to add

**Comment by sensescape** [comment]
<img width="766" alt="screen shot 2016-07-27 at 2 49 10 pm" src="https://cloud.githubusercontent.com/assets/466585/17193754/558156e2-5409-11e6-8198-db564f1c478b.png">

**Comment by sensescape** [comment]
https://github.com/tangrams/tron/commit/107aaa3ee4bec53cca8e8f30f40e72231243e4b5

**Comment by patriciogonzalezvivo** [comment]
yay! thanks!

**Comment by sensescape** [comment]
this is done
