### ISSUE TITLE
building lines too thin

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#25]
Hi! @patriciogonzalezvivo 

I find these lines too thin. Here's a close up:
<img width="113" alt="screen shot 2016-07-27 at 7 30 22 pm" src="https://cloud.githubusercontent.com/assets/466585/17199338/f88331cc-5430-11e6-9ef9-886caf77c259.png">

I think thicker, maybe at minimum 0.5px? (but even 0.5px doesn't look that great) Here's what it looked like before. I like this better. Especially when you leave Manhattan and buildings are not so tall...
<img width="1538" alt="screen shot 2016-07-26 at 11 16 30 am" src="https://cloud.githubusercontent.com/assets/466585/17199353/170de902-5431-11e6-868d-d69fb56bddd5.png">

Now:
<img width="1538" alt="screen shot 2016-07-27 at 7 34 21 pm" src="https://cloud.githubusercontent.com/assets/466585/17199365/34e3cfe6-5431-11e6-8df5-4c2322b47810.png">

I was trying to tweak the width, but couldn't get the result I wanted. 
https://github.com/tangrams/tron/blob/d70df0c56bfad222300faeae9f5dcfc0fd32898f/layers/buildings.yaml#L57
Also not sure I understand the shader for this part.

---

On another note:
I'm now trying to fix this view of the footprints at z15. The lines are so noisy. Not sure what to do here yet... but I'm avoiding same problem as mentioned above. (I'll fix this part, the footprint part)
<img width="785" alt="screen shot 2016-07-27 at 7 38 01 pm" src="https://cloud.githubusercontent.com/assets/466585/17199430/b629dcb2-5431-11e6-9a24-343442eda229.png">

**Comment by sensescape** [comment]
Here's Paris with shorter buildings. Before:
<img width="1538" alt="screen shot 2016-07-26 at 11 10 36 am" src="https://cloud.githubusercontent.com/assets/466585/17200147/a2133ea2-5437-11e6-9142-78592608e83f.png">

Now:
<img width="1538" alt="screen shot 2016-07-27 at 8 25 06 pm" src="https://cloud.githubusercontent.com/assets/466585/17200214/4447e056-5438-11e6-81e9-6182a1ae97bc.png">

**Comment by patriciogonzalezvivo** [comment]
@sensescape the place to tweak that is here https://github.com/tangrams/tron/blob/d70df0c56bfad222300faeae9f5dcfc0fd32898f/layers/buildings.yaml#L115-L116

That is the scale with according to the building height.... so... tall buidlings will get a scale of 1. (100%) which is exactly the same line thickness is specify in `lines:width` ... but shorter once will have a scale of .2  (20%) of the thickness soecify in `lines:width`.

Make sense that in cities with "no so tall buildings" like the beautiful paris building lines are closer to the 20% of the width they suppose to. The solution here is to up the  `WIDTH_MIN` to... let's say 50%~70% (.5 ~.7) and then to modulate the lines augment the `WIDTH_MAX` to 150% (1.5)

**Comment by sensescape** [comment]
Thanks! @patriciogonzalezvivo 
So what about here? How do these affect?
https://github.com/tangrams/tron/blob/d70df0c56bfad222300faeae9f5dcfc0fd32898f/layers/buildings.yaml#L57

**Comment by patriciogonzalezvivo** [comment]
Imagine those as 100%... like the line should look like...
then those values get scale (stretch or shrink) using this percentages (0~1) here https://github.com/tangrams/tron/blob/d70df0c56bfad222300faeae9f5dcfc0fd32898f/layers/buildings.yaml#L115-L116

**Comment by sensescape** [comment]
ahhhh got it!

**Comment by patriciogonzalezvivo** [comment]
: )

**Comment by sensescape** [comment]
this is fixed
