### ISSUE TITLE
circle outline pattern

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#27]
Hi! @patriciogonzalezvivo 

Could we try a circle outline pattern? Also with the ability to set the background color? And with a glow?

<img width="381" alt="screen shot 2016-08-02 at 9 10 35 am" src="https://cloud.githubusercontent.com/assets/466585/17336168/c316edde-5891-11e6-8eef-43aeb3ea056a.png">

**Comment by patriciogonzalezvivo** [comment]
Sure!

I will work on it

**Comment by patriciogonzalezvivo** [comment]
Hi! I add some new "features" to configurate the dot pattern

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fc491c11bf9db8dd642e38456b25daf4c%2Fraw%2Fe5618cf328717ba664ae5cd6470b40e333c90803%2Fscene.yaml

Here are the defaults side by side with something that looks like what you request

![screen shot 2016-08-02 at 4 23 18 pm](https://cloud.githubusercontent.com/assets/346914/17344058/c4e7b7c8-58ce-11e6-8f28-7f77a3857a2a.png)
![screen shot 2016-08-02 at 4 28 43 pm](https://cloud.githubusercontent.com/assets/346914/17344057/c4e6020c-58ce-11e6-9943-6f7deecb6f03.png)

**Comment by patriciogonzalezvivo** [comment]
The more exciting once are `DOTS_TYPE` that could be  `fill` or `stroke` and `DOTS_TILE_STYLE` that can be `tile` or `brick`

**Comment by patriciogonzalezvivo** [comment]
The dot `DOTS_COLOR`change the color of the dots... But... there is "picker'' associated to that : ( so it's really a pain to modify. Like the old days.

I ask @louh and @irealva to add it and is on the way https://github.com/tangrams/tangram-play/issues/444

**Comment by sensescape** [comment]
Nice! Thanks! @patriciogonzalezvivo

**Comment by sensescape** [comment]
Hi! @patriciogonzalezvivo 
Could you take a look? I added it, but it's not drawing:

https://github.com/tangrams/tron/commit/6856933bb29aea0588aae5a185b56616a5223278

<img width="494" alt="screen shot 2016-08-02 at 3 15 02 pm" src="https://cloud.githubusercontent.com/assets/466585/17347367/5f7976a6-58c4-11e6-9d16-bc5032f07b38.png">
