### ISSUE TITLE
Performance optimizations for highway lines

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#28]
The highway has 8 layers of lines:
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L62-L192

lines, outline, highway-dashed, highway-casing1, highway-casing2, highway-casing3, highway-casing4, and highway-glow is underneath all these lines

Tunnels also inherit from this styling.

The dash, casings and glow are turned off for highway links.

plus the traffic animation on top

**Comment by nvkelso** [comment]
This is a refactor for performance. (But it's only on highway roads, so...)

**Comment by nvkelso** [comment]
@bcamper Is this a ship block for Tron going out next month? We think this is only for highways, so it's not being used a lot? Should this be priority1, 2, or 3? Do we make a new shader for it or limit what zooms it is used for, etc.

**Comment by nvkelso** [comment]
Looks like highways (including highway tunnels) are in this road block:
- https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L65-L194

**Comment by patriciogonzalezvivo** [comment]
It's is possible to sit down together and review the logic behind the roads filters, maybe @nvkelso and @sensescape can guide me through it... I want to see how it could be optimize

**Comment by sensescape** [comment]
Yes, of course. First let me deconstruct it for you @patriciogonzalezvivo 
Will send to you soon and we can go over it

**Comment by nvkelso** [comment]
The filters are already simplified over what's in other house styles, I'm most interested in shader performance here for just the highway features.

**Comment by sensescape** [comment]
@patriciogonzalezvivo @bcamper @nvkelso 

Here is z19:
![tron-highways2](https://cloud.githubusercontent.com/assets/466585/18360012/356947f6-75b1-11e6-9305-4163ecde6551.jpg)

the image above shows from the bottom-most layer to the top
highway-glow https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L83-L87
highway-casing4
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L190-L194
highway-casing3
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L185-L189
highway-casing2
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L175-L179
highway-casing1
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L170-L174
highway-dashed
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L77-L82
lines (contains the traffic animation)
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L69-L76

z18
<img width="526" alt="screen shot 2016-09-08 at 10 57 51 am" src="https://cloud.githubusercontent.com/assets/466585/18360483/2158c898-75b3-11e6-9713-9c3e0e3aa8cc.png">

z16-17 is when dashes first appear:
<img width="742" alt="screen shot 2016-09-08 at 10 51 44 am" src="https://cloud.githubusercontent.com/assets/466585/18360296/4db32c04-75b2-11e6-9185-3cc2c0426b8e.png">
<img width="329" alt="screen shot 2016-09-08 at 10 53 15 am" src="https://cloud.githubusercontent.com/assets/466585/18360343/7d5b2132-75b2-11e6-868f-9979c021fcf2.png">

z15 is thick bright casing with the glow underneath
<img width="317" alt="screen shot 2016-09-08 at 10 53 54 am" src="https://cloud.githubusercontent.com/assets/466585/18360374/9ddd5da8-75b2-11e6-9e9e-6c07e2368fee.png">

z14
<img width="335" alt="screen shot 2016-09-08 at 10 54 46 am" src="https://cloud.githubusercontent.com/assets/466585/18360391/b3047252-75b2-11e6-956d-ba3801ae37a2.png">

z13
<img width="253" alt="screen shot 2016-09-08 at 10 55 19 am" src="https://cloud.githubusercontent.com/assets/466585/18360409/c2561256-75b2-11e6-8b53-f087074de323.png">

z12
<img width="164" alt="screen shot 2016-09-08 at 10 55 45 am" src="https://cloud.githubusercontent.com/assets/466585/18360419/d1e4d1d0-75b2-11e6-81cc-ef49c5e568cf.png">

z11
<img width="141" alt="screen shot 2016-09-08 at 10 56 09 am" src="https://cloud.githubusercontent.com/assets/466585/18360434/df7e5a50-75b2-11e6-9ae6-690225cc958b.png">

z10
<img width="132" alt="screen shot 2016-09-08 at 10 56 35 am" src="https://cloud.githubusercontent.com/assets/466585/18360444/eec7cca8-75b2-11e6-81fb-cb9d8780ba69.png">

z9
<img width="113" alt="screen shot 2016-09-08 at 10 57 06 am" src="https://cloud.githubusercontent.com/assets/466585/18360457/fe7086d6-75b2-11e6-98af-d8d05b4d593c.png">

a single line with glow starts at z8
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L54-L63

**Comment by patriciogonzalezvivo** [comment]
@sensescape THANKS! this is super useful!

**Comment by sensescape** [comment]
@patriciogonzalezvivo np! sorry it's so complicated, here's more about highway tunnels, which is basically the same but with some color changes, just in case you need reference for it too:

TUNNELS

https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L124-L163

z19
<img width="829" alt="screen shot 2016-09-08 at 11 22 39 am" src="https://cloud.githubusercontent.com/assets/466585/18361503/ecc17ffe-75b6-11e6-8af8-0892811c3ef2.png">

z18
<img width="600" alt="screen shot 2016-09-08 at 11 25 38 am" src="https://cloud.githubusercontent.com/assets/466585/18361514/fe868c52-75b6-11e6-8adb-29474da05b81.png">

z17
<img width="465" alt="screen shot 2016-09-08 at 11 26 01 am" src="https://cloud.githubusercontent.com/assets/466585/18361525/0ea992c8-75b7-11e6-920d-99cbabef4769.png">

z16
<img width="357" alt="screen shot 2016-09-08 at 11 26 36 am" src="https://cloud.githubusercontent.com/assets/466585/18361541/1e44fd44-75b7-11e6-89e8-9c7da8a58624.png">

z15
<img width="260" alt="screen shot 2016-09-08 at 11 26 54 am" src="https://cloud.githubusercontent.com/assets/466585/18361552/2ad18082-75b7-11e6-92c9-945213e5f7f7.png">

z14
<img width="206" alt="screen shot 2016-09-08 at 11 27 13 am" src="https://cloud.githubusercontent.com/assets/466585/18361565/37409d6c-75b7-11e6-87f6-a352ad35c55d.png">

z13
<img width="118" alt="screen shot 2016-09-08 at 11 27 35 am" src="https://cloud.githubusercontent.com/assets/466585/18361576/43ebcf00-75b7-11e6-84d1-fede291503f9.png">

z12
<img width="216" alt="screen shot 2016-09-08 at 11 27 57 am" src="https://cloud.githubusercontent.com/assets/466585/18361589/51458970-75b7-11e6-8f29-9ae2c21453cb.png">

**Comment by bcamper** [comment]
Thanks @sensescape!

@patriciogonzalezvivo: so the problem here is the very large number of styles (shaders) being used (7 or 8?!), which causes a huge increase in the # of draw calls and lots of overdraw (same pixels being drawn multiple times). Both of those are significant factors in performance degradation. My hope was that you could consolidate as much of this logic as possible, to a fewer number of styles. For example, even if we had multiple styles, if fewer were used per zoom level (so some styles that were more specific to certain combinations of effects at different zoom ranges), that could be potentially be a lot more efficient because there would be fewer draw calls (fewer active styles) at any given time.

**Comment by patriciogonzalezvivo** [comment]
@bcamper sure! I was thinking in consolidating into two layer:
- A: glow + casting4
- B: casting3 + casting2 + casting1 + dashes + trafic light

Why this two? If everything is in one on highways merges... one line will be on top of other... with two will have that behavior only on B. Am I right?

Where I'm worry now is on the zooms... the current transitions contemplate a lot of details fading in/out while zooming. @bcamper what do you think is the best way of handling all those transitions (showing dashes, and traffic line lights):
- A: putting all that logic on the shader: which a bunch of `if` or `smoothstep` 
- B: with `defines`: which eventually bring us to a bunch of different compiled shaders
  -C: (space holder for other ideas)

**Comment by nvkelso** [comment]
Closing this. If there is additional performance to be gained please open a new ticket for v2.1 milestone.

**Comment by bcamper** [comment]
@patriciogonzalezvivo https://github.com/patriciogonzalezvivo were these
changes incorporated yet?

I want to see this happen before launch given the unusually high number of
draw calls.

**Comment by patriciogonzalezvivo** [comment]
Waiting for https://github.com/tangrams/tron/pull/120

**Comment by nvkelso** [comment]
@patriciogonzalezvivo Geraldine and I are done in #120 now, but I've been holding off merging it as it's against dev tiles instead of prod. Since this isn't launched yet I suppose we _could_ merge that now... or you could commit your work against that PR's `nvkelso/vector-tiles-v1` branch. What's easier for you?

**Comment by patriciogonzalezvivo** [comment]
@nvkelso If the `vector-tiles-1v` brunch is ready for merge, I could work directly on it. That's ok for you?

**Comment by patriciogonzalezvivo** [comment]
So... I did a little sketch of how to unify the 4 casting into a single geometry here 

[![161011181616](https://cloud.githubusercontent.com/assets/346914/19283787/409f1842-8fc1-11e6-90fd-469e4144b8cd.png)](http://editor.thebookofshaders.com/?log=161011181616)

And then modify this:

https://github.com/tangrams/tron/commit/f6ec5b52ce97434a3afd7dac51763b2c628d1fe9

Here is how it look **before**

![before](https://cloud.githubusercontent.com/assets/346914/19283927/d4685e44-8fc1-11e6-9713-a3ef80e05ace.gif)

And here is how is now **after** the changes

![after](https://cloud.githubusercontent.com/assets/346914/19283939/e19aeb7c-8fc1-11e6-9fce-7eb2cf674db0.gif)

**Comment by patriciogonzalezvivo** [comment]
Plus a little trick to have similar support for highways tunnels https://github.com/tangrams/tron/commit/1512231725629573c9ea0eced985621dc02de635

**Comment by patriciogonzalezvivo** [comment]
Once @sensescape, review it and tweak it (I can explain it how), I think this can be mark as done : ) !!

**Comment by sensescape** [comment]
Hi @patriciogonzalezvivo ! Let's review together

**Comment by sensescape** [comment]
Completed in the last general v1 vector tiles PR.
