### ISSUE TITLE
noise pattern for water at z15

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#3]
Hi Patricio!

I'm trying to add the pixel noise pattern starting at z15 here:
https://github.com/tangrams/tron/blob/gh-pages/scene/layers/water.yaml#L9-L14

Added:
https://github.com/tangrams/tron/blob/gh-pages/scene/layers/water.yaml#L103-L110
https://github.com/tangrams/tron/blob/gh-pages/scene/main.yaml#L4

Also wanted to try out the pattern you made from your example, but didn't know how to add it:
![noise-texture](https://cloud.githubusercontent.com/assets/466585/16638351/5ed8c80c-439b-11e6-8327-a126f2865a95.jpg)

We can try either pattern, what do you think?
Transition goes ... z13 - stripes end, z14 becomes solid blue, z15 pixel pattern emerges?

FYI I did a similar noise pattern in Refill:
<img width="400" alt="screen shot 2016-07-06 at 4 56 29 pm" src="https://cloud.githubusercontent.com/assets/466585/16638267/b98d8144-439a-11e6-8956-f55290a4b55f.png">
https://github.com/tangrams/refill-style/blob/gh-pages/refill-style.yaml#L690-L715
https://tangrams.github.io/refill-style/#15.0325/37.8134/-122.1547

**Comment by patriciogonzalezvivo** [comment]
What do you think about this?

![00](https://cloud.githubusercontent.com/assets/346914/16698993/40322ad0-451f-11e6-81e1-eaafe5010a1b.gif)

**Comment by patriciogonzalezvivo** [comment]
I was thinking we can reserve the other "randomChar" (that is more "structured") to something in the city... while leaving this patterns that are more chaotic for non-urban areas

**Comment by sensescape** [comment]
I think this can work, if we tone down the colors, so it appears to be moving, but very subtle

**Comment by nvkelso** [comment]
+1

**Comment by sensescape** [comment]
<img width="635" alt="screen shot 2016-07-08 at 4 09 24 pm" src="https://cloud.githubusercontent.com/assets/466585/16703913/64e3e52e-4526-11e6-92c5-c489c18854a3.png">
looking nice!

**Comment by sensescape** [comment]
Too dark! Now that I'm coming back to it. Will make more adjustments.

**Comment by sensescape** [comment]
<img width="659" alt="screen shot 2016-07-08 at 9 34 17 pm" src="https://cloud.githubusercontent.com/assets/466585/16706087/fb9c07a8-4553-11e6-84ec-27ca09a11b58.png">

**Comment by nvkelso** [comment]
+1

**Comment by patriciogonzalezvivo** [comment]
Nice!
