### ISSUE TITLE
 highway-casing# producing errors

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#30]
`highway-casing1`, `highway-casing2`,`highway-casing3` and `highway-casing4` are producing errors. 

<img width="1909" alt="screen shot 2016-08-05 at 10 20 37 am" src="https://cloud.githubusercontent.com/assets/346914/17439505/67e406ec-5af6-11e6-9d2c-41ebe5c934d0.png">

**Comment by sensescape** [comment]
Hmmm but nothing has changed here...
Not getting errors this morning, but had them on Friday evening
<img width="1549" alt="screen shot 2016-08-08 at 10 37 32 am" src="https://cloud.githubusercontent.com/assets/466585/17489717/57572d4e-5d54-11e6-8238-64c4af0bc365.png">

**Comment by sensescape** [comment]
Fixed https://github.com/tangrams/tron/commit/2413d705005ca879ca77ad5c9dca5f3173de707f
Thanks @nvkelso !
