### ISSUE TITLE
Working on early transitions

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#31]
Before 
![01](https://cloud.githubusercontent.com/assets/346914/17441407/e4b86408-5afe-11e6-9e5a-315184248812.gif)

After
![00](https://cloud.githubusercontent.com/assets/346914/17441413/f1595fbe-5afe-11e6-9af5-d5084f557e70.gif)

**Comment by nvkelso** [comment]
+100

**Comment by patriciogonzalezvivo** [comment]
I was thinking in do a fade in and out? What do you think... I don't like how suddenly disapear

**Comment by patriciogonzalezvivo** [comment]
I think this is the final version

![02](https://cloud.githubusercontent.com/assets/346914/17441999/bfd87062-5b01-11e6-9709-2f8793d2e579.gif)

**Comment by nvkelso** [comment]
:)

**Comment by patriciogonzalezvivo** [comment]
Here is the commit https://github.com/tangrams/tron/commit/9942ee44916d19f07193f967f0058569cc0c88da
