### ISSUE TITLE
Diagonal line repeat pattern

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#32]
Hi! @patriciogonzalezvivo 

Could you create a shader with this pattern?
<img width="152" alt="screen shot 2016-08-09 at 10 54 01 am" src="https://cloud.githubusercontent.com/assets/466585/17527335/cb4f4972-5e1f-11e6-8f2e-ad6ebed3d493.png">

**Comment by patriciogonzalezvivo** [comment]
like this http://player.thebookofshaders.com/?log=160815151240

How should we call it?

![dash](https://cloud.githubusercontent.com/assets/346914/17668821/18b2bd12-62d9-11e6-8260-b734bea9f453.png)

**Comment by sensescape** [comment]
Love it!

**Comment by sensescape** [comment]
Diagonal repeat?

**Comment by patriciogonzalezvivo** [comment]
Sorry I forgot about this... you still need it?

**Comment by sensescape** [comment]
yes! thanks!

**Comment by nvkelso** [comment]
This is intended for a new landuse pattern (for instance we have contours still, we could swap those out for this diagonal dashing).

**Comment by nvkelso** [comment]
Blocking https://github.com/tangrams/tron/issues/81.

**Comment by patriciogonzalezvivo** [comment]
https://github.com/tangrams/tron/commit/bcea929f7d20848ffd3d7a735f266fa8947fcb3d Adding a simple `polygons-diagonal-dash` patterns and that same pattern but using elevation data to modulate the dashes width call `elevation-diagonal-dash`

![screen shot 2016-09-01 at 9 34 33 am](https://cloud.githubusercontent.com/assets/346914/18169333/a8c70600-7027-11e6-973b-ee1d8f2b0d55.png)

Here is a link to play w it: https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fecb9d7439c49158cb1fac65c78413743%2Fraw%2F1885a2cb2b81c04aba0544db8814a84c5759a477%2Fscene.yaml#14.0218/41.1679/-74.1495

**Comment by patriciogonzalezvivo** [comment]
Here is a link to play w it: https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fecb9d7439c49158cb1fac65c78413743%2Fraw%2F1885a2cb2b81c04aba0544db8814a84c5759a477%2Fscene.yaml#14.0218/41.1679/-74.1495

**Comment by nvkelso** [comment]
Nice!

@sensescape Is this working enough for you to close this issue?

**Comment by sensescape** [comment]
beautiful @patriciogonzalezvivo ! can't wait to use this. ok @nvkelso will add this then close : )

**Comment by nvkelso** [comment]
Closing this, landuse styling is covered in https://github.com/tangrams/tron/issues/81.

**Comment by patriciogonzalezvivo** [comment]
@sensescape did you get to use this pattern? do you want me to add it to the styles list?

**Comment by sensescape** [comment]
yes @patriciogonzalezvivo  i added it to the golf courses:
https://github.com/tangrams/tron/commit/9e451dd35d7a3e2ce1d8e952b119650e2719c4fb

**Comment by patriciogonzalezvivo** [comment]
awesome!!

**Comment by patriciogonzalezvivo** [comment]
I will make a tangram blocks of it

**Comment by sensescape** [comment]
<img width="845" alt="screen shot 2016-09-07 at 12 46 24 pm" src="https://cloud.githubusercontent.com/assets/466585/18326109/1dd1f682-74f9-11e6-8c2f-ae031973ad6b.png">

**Comment by sensescape** [comment]
looks great! love this texture

**Comment by patriciogonzalezvivo** [comment]
I see that you add the `zoom()` function here https://github.com/tangrams/tron/commit/9e451dd35d7a3e2ce1d8e952b119650e2719c4fb#diff-c925987006b9c7ee2f053206d9aeb0e9R429

But I believe you are not using it... that's right?

**Comment by sensescape** [comment]
I'm not sure... I have zoom here
https://github.com/tangrams/tron/commit/9e451dd35d7a3e2ce1d8e952b119650e2719c4fb#diff-c925987006b9c7ee2f053206d9aeb0e9R433

Am I missing something?

**Comment by patriciogonzalezvivo** [comment]
those values are not apply until you use the `zoom()` function to modulate the value of something

**Comment by sensescape** [comment]
ahhh, yes can we add zoom() ? i meant to use it

**Comment by patriciogonzalezvivo** [comment]
oo sure!

giveme one second that I clean the area...

Do you have a good gold field with lot of elevation changes? all seams preaty flat?

What are you thinking on modulating w `zoom()`?

**Comment by patriciogonzalezvivo** [comment]
Presidio Gold course : ), SF!

**Comment by sensescape** [comment]
want to test it here, in conservation?
https://github.com/tangrams/tron/blob/gh-pages/layers/landuse.yaml#L61-L69

but i'm not sure yet... let's see first
http://localhost:8000/?animated=false#13/37.9031/-122.5840
Mount Tamalpais State park

**Comment by patriciogonzalezvivo** [comment]
haaa.. not for golf course...

take a look on how it look now https://github.com/tangrams/tron/blob/gh-pages/layers/landuse.yaml#L387-L401

to interpolate some value with zoom level take a look to this: http://tangrams.github.io/blocks/#functions-zoom

For mixing the `function-zoom` do this https://github.com/tangrams/tron/blob/gh-pages/layers/landuse.yaml#L375
For setting the interpolation do this https://github.com/tangrams/tron/blob/gh-pages/layers/landuse.yaml#L378-L381
And to use it to interpolate something using zoom do something like this: https://github.com/tangrams/tron/blob/gh-pages/layers/landuse.yaml#L384

**Comment by sensescape** [comment]
Ahhhh I'll give it a try, we're updating the green areas tomorrow:
https://github.com/tangrams/tron/issues/72 

So I can test it when Nathaniel and I update. Thanks! @patriciogonzalezvivo
