### ISSUE TITLE
Animated POis

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#33]
So here are some generative POis

[![](http://thebookofshaders.com/log/160805190306.png) click me](http://player.thebookofshaders.com/?log=160805190306)
[![](http://thebookofshaders.com/log/160805194757.png) click me](http://player.thebookofshaders.com/?log=160805194757)

Yay shaders. On the down side, they are computationally heavy! Making SDFs from scratch is expensive... so we can't use them. Buuu.

BUT if we pre-generate SDF based on the lovely icons @sensescape is working on, we can save enough GPU power to animate some of them. Exciting! 

How? I made a [ImageMagic](http://www.imagemagick.org/script/index.php) script to transform black/white icons into SDF images. [Here is the `sdf.sh` script](https://github.com/tangrams/tron/blob/gh-pages/images/sdf.sh) should work on any POSIX computer w image magic install.

What it does? Take the contours of a B/W image and erode the borders in.... until they touch each other and then set a gradient from the original borders of the image to this "middle parts".  

<img width="1055" alt="screen shot 2016-08-18 at 9 36 26 am" src="https://cloud.githubusercontent.com/assets/346914/17775680/56d75422-6527-11e6-92e6-5e242f13eddd.png">

The end up looking like our elevation tiles... we can mountain the hell of any SVG. Crazy right?
Hooray for imageMagic.

Then user the magic of shaders we can take advantage of this extra "data" we add to the image to do things like this:

[![](http://thebookofshaders.com/log/160818140257.png) click me](http://player.thebookofshaders.com/?log=160818140257)

[![](http://thebookofshaders.com/log/160817211857.png) click me](http://player.thebookofshaders.com/?log=160817211857)

Is not that I can do A LOT with this SDF data, but the more pre-process we do to the images the less intense is in the client.

For example:
- The rings are not 100% centered (sometimes centered stuff doesn't look great)... so the structure of the icons need to be **VERY standardize**. 
- I'm masking the out ring of the icon, that's done in the shader. We could color-code the icons to mark what things should animate and how. That again implies more work on the making of the icons sprites.
- One of the most expensive things of this circular animations is calculating the angle each pixel is from the center... for that I'm using an `atan2` functions that's not particularly cheap. So this should be add to the TODO list of things to pre process on the sprites POIs. How? Well this is probably to much to ask for image magic (at lease, I can't imagine a way to do it now)... BUT we can use [glslViewer](https://github.com/patriciogonzalezvivo/glslViewer) to construct this kind of maps.
- Then we will probably want a sort of JS script on the POIs label, to pass values to the poi through the color, so we can cherry pict, what icons should be animated, how, when, etc. We can even make things animate when they are not in the center of the screen (for readability) and those kind of things. Fancy right?
### Conclusion

The animations will look cool, but need some preprocessing work to be "affordable" in terms of efficiency and more work for @sensescape, @nvkelso and me encoding data in the POIs icons. fun times!

It worth it? Well... is not a priority... visually will be just a detail. BUT I think is a cool experiment that will teach us new ways of making a pipeline for "smarter" POIs icons! Smarter like **more reusable**, by designing basic motives that can be mixed with shields, billboards and other composition techniques like borders, shadows, and some other font rendering tricks).

That's all

cc @bcamper

**Comment by bcamper** [comment]
Thanks @patriciogonzalezvivo, let's catch up on this later today.

**Comment by nvkelso** [comment]
I really like the the colors, shapes, and animations in http://player.thebookofshaders.com/?log=160805190306, they're beautiful!

But I worry about them at 18px size for the smaller map icons (and there are dozens of those on the map screen at any one time).

Maybe we can use this approach for some of the routing and search result icons, and for icons that are tapped on, maybe they get bigger and animated like this? Just like we were talking of using the submarine cable line style for the routeline?

**Comment by sensescape** [comment]
Beautiful! @patriciogonzalezvivo 
Yes can we see them animate on 18px size on the current map? Curious to see how these work on smaller scale. Also plan to make small, medium, large versions of icons to add to sprite sheet. 18px will be small. 36px medium maybe. Have to play with the sizing.

**Comment by patriciogonzalezvivo** [comment]
Thanks for the feedback... you can use this url http://player.thebookofshaders.com/?log=160818175530 and scale down your browser windows to see it in deferent scales

**Comment by sensescape** [comment]
Wow! I love it! It's gorgeous
