### ISSUE TITLE
unable to specify dot size

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#34]
Hi @patriciogonzalezvivo 
Can't control dot size here:
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L557-L566

I think it might  be because it's specified in 2 names here, DOT_SIZE and DOTS_SIZE
https://tangrams.github.io/blocks/lines/dots.yaml

**Comment by patriciogonzalezvivo** [comment]
try now : )
