### ISSUE TITLE
Airport icon at high zooms

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#37]
To transition from the big color'd gradient ball.

**Comment by sensescape** [comment]
<img width="562" alt="screen shot 2016-09-06 at 1 32 55 pm" src="https://cloud.githubusercontent.com/assets/466585/18289983/84485ea6-7436-11e6-8667-3df252ff3990.png">
<img width="641" alt="screen shot 2016-09-06 at 1 33 02 pm" src="https://cloud.githubusercontent.com/assets/466585/18289997/8b720272-7436-11e6-8791-98d1d3917588.png">
<img width="831" alt="screen shot 2016-09-06 at 1 33 06 pm" src="https://cloud.githubusercontent.com/assets/466585/18289999/92de2d38-7436-11e6-9d1c-e410c7298358.png">
