### ISSUE TITLE
I broke landuse layers

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#4]
Hi @sensescape, I have been working on the layers... renaming to have a consisten structure we can easily escalate.

Unfortunately I broke the landuse layers : S
Can you give them a look?
Use to be like this:

<img width="1441" alt="screen shot 2016-07-08 at 1 53 53 pm" src="https://cloud.githubusercontent.com/assets/346914/16696710/1b7ee382-4514-11e6-8b94-3dcb9e0ee71d.png">

And now looks like this:

<img width="1439" alt="screen shot 2016-07-08 at 1 53 59 pm" src="https://cloud.githubusercontent.com/assets/346914/16696661/eae33598-4513-11e6-8b9b-5f4aad1ad14e.png">

I'm still working in the rules and conventions, I'm writing them [here](https://github.com/tangrams/tron/blob/gh-pages/README.md). Tellme if make sense?

**Comment by patriciogonzalezvivo** [comment]
Making turning all layers visible: https://github.com/tangrams/tron/blob/gh-pages/scene/layers/landuse.yaml#L8

And in red... so you can debug it

<img width="842" alt="screen shot 2016-07-08 at 3 25 43 pm" src="https://cloud.githubusercontent.com/assets/346914/16699158/66f4069c-4520-11e6-882a-0152b0f30176.png">

**Comment by sensescape** [comment]
So first I tried commenting everything below the top level, and at the top level, drawing rules are set up for all of landuse. It's drawing everything red.
<img width="610" alt="screen shot 2016-07-08 at 4 55 55 pm" src="https://cloud.githubusercontent.com/assets/466585/16704545/2bd174f2-452d-11e6-84e2-17f4028a13cf.png">
<img width="630" alt="screen shot 2016-07-08 at 4 56 09 pm" src="https://cloud.githubusercontent.com/assets/466585/16704548/33147bec-452d-11e6-9e9f-3bccb5241144.png">

**Comment by sensescape** [comment]
but i don't want to draw everything so i make it visible:false
<img width="418" alt="screen shot 2016-07-08 at 5 00 48 pm" src="https://cloud.githubusercontent.com/assets/466585/16704586/ca8d125e-452d-11e6-93fc-43b45764a2b6.png">
<img width="436" alt="screen shot 2016-07-08 at 5 00 42 pm" src="https://cloud.githubusercontent.com/assets/466585/16704588/d1408d7e-452d-11e6-8c6b-190fcedee289.png">

**Comment by sensescape** [comment]
(with my top level drawing rules from above remaining the same) i then tried uncommenting the first filter for tier1 and visible:true
<img width="514" alt="screen shot 2016-07-08 at 5 06 41 pm" src="https://cloud.githubusercontent.com/assets/466585/16704638/9661f8f4-452e-11e6-819e-ace84feeb9a7.png">
, but it doesn't draw anything
<img width="606" alt="screen shot 2016-07-08 at 5 05 31 pm" src="https://cloud.githubusercontent.com/assets/466585/16704639/a42da5b4-452e-11e6-8e61-bcbf983f92af.png">

**Comment by sensescape** [comment]
i also tried a simpler filter, just to test, still no draw:
<img width="297" alt="screen shot 2016-07-08 at 5 13 00 pm" src="https://cloud.githubusercontent.com/assets/466585/16704680/5f8e813e-452f-11e6-955e-0aab31f3c585.png">
<img width="226" alt="screen shot 2016-07-08 at 5 13 18 pm" src="https://cloud.githubusercontent.com/assets/466585/16704683/648fd3b8-452f-11e6-9a5e-c58d41a5c68e.png">

**Comment by sensescape** [comment]
I then tried it without the top level drawing rules, and uncommenting tiers 1 to 4
seems like only the THIN STRIPES shader is drawing, and not the elevation-stripes
<img width="522" alt="screen shot 2016-07-08 at 5 23 24 pm" src="https://cloud.githubusercontent.com/assets/466585/16704776/b47a546a-4530-11e6-9fb1-6efd53ba0a85.png">

**Comment by sensescape** [comment]
then i thought I'm missing style: landuse from the top level, but after i added it, still no draw
<img width="485" alt="screen shot 2016-07-08 at 5 28 36 pm" src="https://cloud.githubusercontent.com/assets/466585/16704854/c46549ec-4531-11e6-8e5a-bea03af16178.png">
<img width="907" alt="screen shot 2016-07-08 at 5 30 34 pm" src="https://cloud.githubusercontent.com/assets/466585/16704857/c9be79d6-4531-11e6-8a70-2295d458185a.png">

**Comment by sensescape** [comment]
I think it doesn't like style:landuse at the top level draw. When I uncommented out style:landuse at the top. Polygons from tiers1-4 started to draw.

**Comment by sensescape** [comment]
Fixed! I removed style:landuse at the top level. But I had to add it to the layers below
https://github.com/tangrams/tron/commit/fb2ecb919ccc483b939492cf24fdaac44d20e819
Does this break the structure you wanted to set up? 
<img width="409" alt="screen shot 2016-07-08 at 7 52 19 pm" src="https://cloud.githubusercontent.com/assets/466585/16705669/882d3e8a-4545-11e6-84e7-292464658754.png">

**Comment by patriciogonzalezvivo** [comment]
YAY! you are amazing! The structure is preserve! I just make a note for one of the names that should be `-forest-national` instead of `-national-forest` just because of the tree structure

**Comment by sensescape** [comment]
Ok! Thanks!
