### ISSUE TITLE
Add various religion icons

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#43]
Mostly copy them over from Walkabout icons.

**Comment by sensescape** [comment]
<img width="621" alt="screen shot 2016-09-01 at 12 59 10 pm" src="https://cloud.githubusercontent.com/assets/466585/18184661/f615a160-704e-11e6-90ee-3daba107cfb9.png">
<img width="529" alt="screen shot 2016-09-01 at 2 15 37 pm" src="https://cloud.githubusercontent.com/assets/466585/18184688/186ec0b6-704f-11e6-964c-f1fc5105a276.png">
<img width="517" alt="screen shot 2016-09-01 at 2 20 19 pm" src="https://cloud.githubusercontent.com/assets/466585/18184722/423f00c2-704f-11e6-9eae-b510b801317e.png">
<img width="585" alt="screen shot 2016-09-01 at 2 21 19 pm" src="https://cloud.githubusercontent.com/assets/466585/18184758/624fb956-704f-11e6-9e53-bc3e37960f04.png">
