### ISSUE TITLE
Townspots icons sometime cut off

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#47]
See around NYC

**Comment by nvkelso** [comment]
Related: https://github.com/tangrams/tron/issues/75

**Comment by sensescape** [comment]
<img width="337" alt="screen shot 2016-09-06 at 12 48 27 pm" src="https://cloud.githubusercontent.com/assets/466585/18288453/4f279bc0-7430-11e6-90bb-37f52a4284b1.png">
<img width="508" alt="screen shot 2016-09-06 at 12 48 49 pm" src="https://cloud.githubusercontent.com/assets/466585/18288457/54bebdc0-7430-11e6-8538-072f930ec9aa.png">
