### ISSUE TITLE
Too many church labels everywhere

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#50]
- They shouldn't show up before zoom 13.
- They sometimes only have icons and not text

**Comment by nvkelso** [comment]
Especially early in Tokyo!

**Comment by patriciogonzalezvivo** [comment]
Tron have no god... just a man name [Kevin Flynn](http://tron.wikia.com/wiki/Kevin_Flynn) 
which is pretty dam cool.

; )

![kevin_flynn___tron__legacy_by_benji3o3-d6d3nam](https://cloud.githubusercontent.com/assets/346914/18170877/e8b125ce-702d-11e6-8895-87e38b112320.gif)
![flynn](https://cloud.githubusercontent.com/assets/346914/18170878/e8b3e4b2-702d-11e6-8e83-989740352cc2.gif)
![rqchl2](https://cloud.githubusercontent.com/assets/346914/18170884/eec80054-702d-11e6-97d7-3157beae609b.gif)

**Comment by sensescape** [comment]
Done!
