### ISSUE TITLE
Transition hospital, pedestrian, and other landuse colors

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#56]
It's very bold at earlier zooms!

Needs to improve color with respect to the hospital icon, too.

**Comment by nvkelso** [comment]
Including university colors – vibrating with their icon + text labels.

**Comment by nvkelso** [comment]
Probably also substation?

**Comment by sensescape** [comment]
<img width="925" alt="screen shot 2016-09-02 at 3 15 21 pm" src="https://cloud.githubusercontent.com/assets/466585/18219644/18fea8e4-7120-11e6-9480-f166d58a7849.png">
<img width="551" alt="screen shot 2016-09-02 at 3 14 29 pm" src="https://cloud.githubusercontent.com/assets/466585/18219649/22a9f812-7120-11e6-80e7-a1e6015bb1c3.png">
<img width="504" alt="screen shot 2016-09-02 at 3 12 06 pm" src="https://cloud.githubusercontent.com/assets/466585/18219655/2c56b49a-7120-11e6-8bf3-1fd8f1c01ce3.png">
