### ISSUE TITLE
Add subway entrance icon

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#59]
Probably the generic turned orange?

**Comment by sensescape** [comment]
<img width="994" alt="screen shot 2016-09-01 at 11 36 58 am" src="https://cloud.githubusercontent.com/assets/466585/18179672/79f59e34-7038-11e6-95bb-7fa0a6c4b76c.png">

https://tangrams.github.io/tron/?animated=false#19/48.87353/2.32817
