### ISSUE TITLE
Add dot shader block

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#6]
Sketch mixing dots in overlay mode first, then create custom mixes

mix dot pattern shader
<img width="132" alt="screen shot 2016-07-11 at 2 25 45 pm" src="https://cloud.githubusercontent.com/assets/466585/16747373/b65de43c-4773-11e6-9579-d584f13f62b7.png">

(but keep modular so can use any of the dots without mix)

**Comment by sensescape** [comment]
Should we make it like the weaving I'm currently doing with stripes. One elevation-dots with plain dots? Or not? What do you think? We'll probably have to try both and see what looks best.

**Comment by nvkelso** [comment]
I really like the 3 up, H and circle patterns this one makes (in your example image above).

**Comment by sensescape** [comment]
me too!

**Comment by sensescape** [comment]
Hi @patriciogonzalezvivo 
Trying to import dots, but not drawing (testing it on universities)
https://github.com/tangrams/tron/commit/d59bcb42ee47063e18d31d1fb260e80637aba092

Looking for an example of how to write it into the styles here:
http://tangrams.github.io/blocks/#patterns

**Comment by patriciogonzalezvivo** [comment]
Solved : ) https://github.com/tangrams/tron/commit/c8e5bbd0ed306f6c08c42532dfb0e3a7efaa1787#diff-1f9cc41599bcddf89362bbfc18196759L19

**Comment by sensescape** [comment]
Thanks!!
