### ISSUE TITLE
Add grid shader block

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#7]
Sketch mixing grids in overlay mode first, then create custom mixes

mix grids like this
<img width="164" alt="screen shot 2016-07-11 at 2 25 52 pm" src="https://cloud.githubusercontent.com/assets/466585/16747430/fa1c4db2-4773-11e6-807f-f3c3ebbf01c5.png">

(but keep modular so can use any of the grids without mix)

**Comment by sensescape** [comment]
Hi! @patriciogonzalezvivo 
I'd love to add this grid that you made here:
<img width="233" alt="screen shot 2016-07-13 at 4 38 33 pm" src="https://cloud.githubusercontent.com/assets/466585/16823381/9ba450b2-4918-11e6-89e9-a1214f26439e.png">
http://player.thebookofshaders.com/?log=160705205527

Also, can we have the option of rotating the grid to create patterns like above?

**Comment by patriciogonzalezvivo** [comment]
@sensescape rotating... is kind of expensive.
I will work on adding this pattern

**Comment by patriciogonzalezvivo** [comment]
Adding the style here: https://github.com/tangrams/tron/commit/c5e636fbf6abd232834e41e8f9bc0fabf00e6b23

Try it out here:
https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fd296ec57e0d1865b36f18cdfc0c4d5ce%2Fraw%2F56dd5eff0d1144e3846e17c2f53e7cbe5ae7b9ec%2Fscene.yaml#15.988402002304657/40.7064/-74.0146

![screen shot 2016-07-14 at 10 09 05 am](https://cloud.githubusercontent.com/assets/346914/16842330/153271e2-49ab-11e6-965d-ec44beec767a.png)

**Comment by patriciogonzalezvivo** [comment]
@sensescape [here](https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fbb15407ca2b456d62065669f76bfe8ab%2Fraw%2Fd25fcbf55f017466a4900cb2a3e5356d7182a94a%2Fscene.yaml#14.049062818784845/37.8464/-122.5051) there is an experimental version of this stripe modulated by the terrain
<img width="1124" alt="screen shot 2016-07-14 at 10 14 53 am" src="https://cloud.githubusercontent.com/assets/346914/16842573/f12deabe-49ab-11e6-9d98-9c8dfa238255.png">
