### ISSUE TITLE
Copy over new Bubble Wrap branch forest/park landuse color logic

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#72]
What we had was wrong, it's been fixed (mostly).

Specifically national parks versus parks versus forest versus natural_forest. Also complicated with v1 tiles release.

**Comment by sensescape** [comment]
this is done

https://github.com/tangrams/tron/commit/744f390c6c1f750d5870aea6c97861471dfcf112

<img width="940" alt="screen shot 2016-09-08 at 4 46 42 pm" src="https://cloud.githubusercontent.com/assets/466585/18370719/106b0c4a-75e4-11e6-9d60-d455a8972eae.png">
