### ISSUE TITLE
Another pass on road colors in landuse

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#73]
For instance the hospital in Eureka CA shows red roads at zoom 13 with no landuse, then at z14 landuse is shown but black roads, and at z15+ it's as expected with landuse + red roads.

**Comment by sensescape** [comment]
also check these
<img width="359" alt="screen shot 2016-09-06 at 5 55 38 pm" src="https://cloud.githubusercontent.com/assets/466585/18321563/54b6d5de-74e3-11e6-8bf4-5f4b274c279c.png">
http://localhost:8000/?animated=false#18/52.54468/13.41683

<img width="379" alt="screen shot 2016-09-06 at 4 01 51 pm" src="https://cloud.githubusercontent.com/assets/466585/18321582/6bee8828-74e3-11e6-9908-2fde9fa00025.png">

**Comment by sensescape** [comment]
this is done

<img width="589" alt="screen shot 2016-09-07 at 11 00 49 am" src="https://cloud.githubusercontent.com/assets/466585/18323059/b1506484-74ea-11e6-9ad5-941783d56d3f.png">
<img width="722" alt="screen shot 2016-09-07 at 11 02 32 am" src="https://cloud.githubusercontent.com/assets/466585/18323065/b7f0eeb2-74ea-11e6-8cae-38ff82f5816b.png">
<img width="401" alt="screen shot 2016-09-07 at 11 02 38 am" src="https://cloud.githubusercontent.com/assets/466585/18323069/bcd188ce-74ea-11e6-85d3-5c74770f3cc7.png">
