### ISSUE TITLE
Change contours in protected areas to general landuse shader

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#74]
Performance, consistency (early zooms it's not contoured).

See SF Peninsula Watershed just south of SF.

**Comment by nvkelso** [comment]
Decision: Switch to default landuse shader.

**Comment by sensescape** [comment]
Before:
<img width="905" alt="screen shot 2016-08-31 at 6 02 01 pm" src="https://cloud.githubusercontent.com/assets/466585/18151569/16880db6-6fa5-11e6-8955-9676911f954e.png">

After:
<img width="793" alt="screen shot 2016-08-31 at 6 01 48 pm" src="https://cloud.githubusercontent.com/assets/466585/18151576/1fe245de-6fa5-11e6-9e39-e84e4141cb79.png">

Must use this contour shader for something else later:
https://github.com/tangrams/tron/commit/0842d26e599927321f36760d47c6e28dd92429ae
