### ISSUE TITLE
Improve city labels 

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#75]
Custom townpots (not just circles)?
Match color between icon and text?

**Comment by sensescape** [comment]
<img width="447" alt="screen shot 2016-09-06 at 12 44 33 pm" src="https://cloud.githubusercontent.com/assets/466585/18288394/fe703f8e-742f-11e6-83c5-44591d23b3ae.png">
<img width="438" alt="screen shot 2016-09-06 at 12 44 49 pm" src="https://cloud.githubusercontent.com/assets/466585/18288402/0630b258-7430-11e6-8c91-8586d71b09ce.png">
<img width="467" alt="screen shot 2016-09-06 at 12 45 11 pm" src="https://cloud.githubusercontent.com/assets/466585/18288413/10b9f4aa-7430-11e6-98bb-825abefb884f.png">
