### ISSUE TITLE
Adjust treatment of land & water at zoom 0 and 1

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#77]
Adjust the number of lines? Colors? Line thickness? Zoom 2 looks better (like the lines are in the features, not obscuring the features).

**Comment by patriciogonzalezvivo** [comment]
Like this?

Before:
![screen shot 2016-09-01 at 9 46 23 am](https://cloud.githubusercontent.com/assets/346914/18169883/1ae2f5a8-702a-11e6-9f7f-691ba7c4cb85.png)

After
![screen shot 2016-09-01 at 9 52 37 am](https://cloud.githubusercontent.com/assets/346914/18169888/20a10430-702a-11e6-91ae-3adac6cdee96.png)

**Note**: If @nvkelso like it, here are the values for `water` and `earth-early`
https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F37aa46e8ec8dfb9258c1714b1f82f51d%2Fraw%2Fffecc8564f755166a949594c7ba829912810de81%2Fscene.yaml#1.1405/6.7/-31.1

**Comment by patriciogonzalezvivo** [comment]
@nvkelso what are your thought on the solution? should I apply the changes?

**Comment by nvkelso** [comment]
Yes, much better!

**Comment by patriciogonzalezvivo** [comment]
https://github.com/tangrams/tron/commit/6ae9dae82d6b5a4e3d603e23b48057675933a798

**Comment by sensescape** [comment]
looks good!
