### ISSUE TITLE
Remove unused fonts from main tron.yaml

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#78]
We think we're using just 5 of the dozen fonts. The other should be removed.
- Orbitron
- Cairo
- Audiowide
- Aldrich
- Abel

Audit and remove not-used.

**Comment by nvkelso** [comment]
+1

**Comment by sensescape** [comment]
this is done
https://github.com/tangrams/tron/commit/b96a9acbd20b295863ff645180e2338dc8fc3e46
