### ISSUE TITLE
Add building labels

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#79]
There's a commented out layer for this, rescue it! Probably from another house style file, though?

**Comment by sensescape** [comment]
this is done

<img width="1062" alt="screen shot 2016-09-07 at 11 49 23 am" src="https://cloud.githubusercontent.com/assets/466585/18324397/281b1874-74f1-11e6-890e-3f4c4f3499e7.png">
<img width="906" alt="screen shot 2016-09-07 at 11 47 08 am" src="https://cloud.githubusercontent.com/assets/466585/18324403/33e04f6c-74f1-11e6-8cd4-466507f29cb4.png">
