### ISSUE TITLE
Create tron glow lines shader

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#8]
Looks like this:
<img width="406" alt="screen shot 2016-07-12 at 10 26 17 am" src="https://cloud.githubusercontent.com/assets/466585/16776696/68116972-481b-11e6-950c-858e9333c7cd.png">

For here:
<img width="371" alt="screen shot 2016-07-12 at 10 27 58 am" src="https://cloud.githubusercontent.com/assets/466585/16776708/7991342a-481b-11e6-8808-91a9357b9e75.png">

**Comment by patriciogonzalezvivo** [comment]
![screen shot 2016-07-14 at 9 32 16 am](https://cloud.githubusercontent.com/assets/346914/16841150/e0b273ae-49a5-11e6-898c-1fc776bb77a1.png)
Like this? http://thebookofshaders.com/edit.php?log=160714133247

**Comment by patriciogonzalezvivo** [comment]
@sensescape I add a glow line style ready to be use ; ) here https://github.com/tangrams/tron/commit/7f400d5f48dafccf622eb1b4aa65c441f3df1e41#diff-00a5904308f10281f68148761eb5ed90L21

Try it out first here (see that you need to change the `inlay` for `add` on the blend mode):
https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F34214efaf9448fd7ac38fefb47837867%2Fraw%2F856e46dedaf2922550f9dbcc40a4107ebf8a92f4%2Fscene.yaml#17/40.70359/-74.01217

**Comment by sensescape** [comment]
yay!
