### ISSUE TITLE
Adjust icon size per zoom for some kinds

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#80]
Let's keep this to train stations and airports only for initial v2 release.

**Comment by nvkelso** [comment]
We got the `xl` sizing to work out of Illustrator for the **train stations** (but the asset in AI still needs to be larger so the scene file size isn't blurry). We should also add this for airports.

**Comment by sensescape** [comment]
did this for stations

<img width="584" alt="screen shot 2016-09-13 at 3 23 16 pm" src="https://cloud.githubusercontent.com/assets/466585/18495208/eea7e81c-79d0-11e6-8065-8232f428048c.png">
