### ISSUE TITLE
Use new landuse shader for some kinds

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#81]
Man made? (not for nature)

**Comment by sensescape** [comment]
diagonal dash now being used in landuse golf_course:
<img width="960" alt="screen shot 2016-09-06 at 2 10 01 pm" src="https://cloud.githubusercontent.com/assets/466585/18291252/c1c799c2-743b-11e6-8b5b-912982b866d3.png">
https://github.com/tangrams/tron/commit/9e451dd35d7a3e2ce1d8e952b119650e2719c4fb
