### ISSUE TITLE
Add road car animation for all roads at zoom 18+

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#84]

**Comment by patriciogonzalezvivo** [comment]
blocked by https://github.com/tangrams/tron/issues/22

**Comment by patriciogonzalezvivo** [comment]
@nvkelso, I need more information on what "all roads" are. Can you make a list of what roads in what zoom levels need to be animated.

@bcamper will help me to make rules for it : )

thanks both

**Comment by nvkelso** [comment]
@patriciogonzalezvivo For the minor streets at z18+ that you just added, can it be a single lane of traffic in each direction (now it's 2), please? Also less frequent, more spaced apart movement?

**Comment by patriciogonzalezvivo** [comment]
So one direction even if they are non-oneway? Could we have detail which roads are applies this https://github.com/tangrams/tron/issues/22 issue ??

Tweaking the animating will imply more branches of the shader, which we are trying to reduce.

**Comment by nvkelso** [comment]
Let's not animate parking lot roads (`kind : minor_road, service : parking_aisle`), see https://tangrams.github.io/tron/#19/37.79928/-122.39810.

**Comment by nvkelso** [comment]
And remove animation from airport runways, taxiways: (`kind : minor_road, aeroway : taxiway` or `kind : minor_road, aeroway : runway`): https://tangrams.github.io/tron/#18/37.61826/-122.37850

**Comment by nvkelso** [comment]
And remove animation from service roads / piers: (`kind : minor_road, highway : service`): https://tangrams.github.io/tron/#18/37.80683/-122.44283

**Comment by nvkelso** [comment]
Major roads that are tertiary (`kind : major_road, highway : tertiary`) should receive animation at zoom 17, e.g. Delores and 24th: https://tangrams.github.io/tron/#17/37.75152/-122.42380

**Comment by nvkelso** [comment]
For the minor roads, is it possible to show 25% as many (remove most) cars, and to slow them down compared to the major roads? This area looks like Uber robot cars are operating a embargo around the neighbourhoods. Else take them off? https://tangrams.github.io/tron/#18/37.75894/-122.42324

**Comment by nvkelso** [comment]
#22 has been resolved, this issue is no longer blocked.

**Comment by patriciogonzalezvivo** [comment]
No traffic animation in parking lots, airport runways, taxiways and services roads https://github.com/tangrams/tron/commit/102b16e8de6a1e61020f8d7fe8ae9df8b917a4b9

**Comment by patriciogonzalezvivo** [comment]
Adding traffic on all mayor roads including tertiary... This may need polish https://github.com/tangrams/tron/commit/80c3db35c5b6982b3457a21efedd11cbda7b1fbe

**Comment by patriciogonzalezvivo** [comment]
@nvkelso LOL for uber robot cars operating a embargo
Those changes will require 2 more custom shader styles : /

**Comment by nvkelso** [comment]
@patriciogonzalezvivo proposed in https://github.com/tangrams/tron/issues/22#issuecomment-244092397 to move some of the speed, 2 lanes versus 1 lane, etc into color channels so we could reduce the number of shaders.

**Comment by patriciogonzalezvivo** [comment]
@nvkelso I speed up highways... and slow down major roads... and super slow down minor roads https://github.com/tangrams/tron/commit/b7f0d08c8808e2bf9a9a1250dafdf332678ec423 Also echa one of them fade in accordingly to the zoom level they appear... tellme how that looks 

![01](https://cloud.githubusercontent.com/assets/346914/18687905/27fdc2d8-7f50-11e6-93d4-1fc6c84b882a.gif)

**Comment by patriciogonzalezvivo** [comment]
@nvkelso excited to close this issue. Let's keep in the back of ours minds that this add 4 extra shader styles and is a place to start optimizing in future iterations

**Comment by nvkelso** [comment]
@patriciogonzalezvivo Huge improvement, thank you! It's a little hard to see at zoom 14 but decent at 15. Let's call it done.
