### ISSUE TITLE
Add some more car animation on major roads only z14

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#85]

**Comment by patriciogonzalezvivo** [comment]
blocked by https://github.com/tangrams/tron/issues/22

**Comment by nvkelso** [comment]
#22 has been resolved, this issue is no longer blocked.

**Comment by patriciogonzalezvivo** [comment]
Added traffic animation for major roads after zoom 14 https://github.com/tangrams/tron/commit/80c3db35c5b6982b3457a21efedd11cbda7b1fbe

**Comment by nvkelso** [comment]
Looks like animation is **always** on now, even when the `global.animation` is set to false.

**Comment by patriciogonzalezvivo** [comment]
This commit (https://github.com/tangrams/tron/commit/3609eeead65bbacfd40a278f05214d59f3f8b650) removes any all traffic when `global.animation` is off

**Comment by nvkelso** [comment]
The traffic on tertiary roads was outside of the roadbed. Fixed in 40ed038f691575198e31c4dba3bcf39e2f58cdb4 to thicken up those tertiary roads.
