### ISSUE TITLE
Add glow to airport runway lights

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#88]
Hi @patriciogonzalezvivo !

Could we add glow to runway-dots:
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L462

<img width="831" alt="screen shot 2016-09-06 at 1 33 06 pm" src="https://cloud.githubusercontent.com/assets/466585/18290136/30f79914-7437-11e6-834a-b74f07da9bec.png">
<img width="641" alt="screen shot 2016-09-06 at 1 35 55 pm" src="https://cloud.githubusercontent.com/assets/466585/18290145/371ba60a-7437-11e6-8a90-9da35443abdd.png">

**Comment by patriciogonzalezvivo** [comment]
They will need to repeat less often... they are too close...
Also I will make a custom shader that unifies the `dashes` and `glow`

**Comment by patriciogonzalezvivo** [comment]
We should do the same (unifying the road, glow and dashes) for a lot of other roads that will reduce the geometry a lot.

**Comment by sensescape** [comment]
Ok!

**Comment by patriciogonzalezvivo** [comment]
mmmmm... in seconds thoughts... I can not "flat" all this layers (background glow, road, dashes) because on cross sections they hide each other... that seams like a big down for that : (

I will submit a proposal for glowing dashes alone

**Comment by patriciogonzalezvivo** [comment]
Ok 
[Here is an example.](https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F7bb9aa6f1ce67089ad4a472cf384eed5%2Fraw%2F38ec44f0ee1f88525a546f74c7db3c0b3c63460b%2Fscene.yaml#15.7622/40.7760/-73.8714) you probably want to add some width to the dots line

[![screen shot 2016-09-07 at 2 48 44 pm](https://cloud.githubusercontent.com/assets/346914/18324406/5c23774c-750a-11e6-8fa2-770b3fd9f453.png)](https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F7bb9aa6f1ce67089ad4a472cf384eed5%2Fraw%2F38ec44f0ee1f88525a546f74c7db3c0b3c63460b%2Fscene.yaml#15.7622/40.7760/-73.8714)

**Comment by patriciogonzalezvivo** [comment]
@sensescape [here](https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fd32b9e38565a3e4d2c0f3d4755083183%2Fraw%2Fb9c104491c82d7b864a93cfe40c92760fdf31686%2Fscene.yaml#13.9978/40.7691/-73.8730) is almost the same code but with an animation... hope you like it

[![00](https://cloud.githubusercontent.com/assets/346914/18324735/f4fd28ae-750b-11e6-9112-929007864058.gif)](https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fd32b9e38565a3e4d2c0f3d4755083183%2Fraw%2Fb9c104491c82d7b864a93cfe40c92760fdf31686%2Fscene.yaml#13.9978/40.7691/-73.8730)

**Comment by patriciogonzalezvivo** [comment]
Let me know if you want me to add it

**Comment by sensescape** [comment]
Nice! Thanks @patriciogonzalezvivo 
Ok

**Comment by patriciogonzalezvivo** [comment]
https://github.com/tangrams/tron/commit/9c5d8a4e7965139c8b5adafeb16741fefd74ada1
