### ISSUE TITLE
roads casings color work

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#89]
<img width="379" alt="screen shot 2016-09-06 at 4 01 51 pm" src="https://cloud.githubusercontent.com/assets/466585/18294042/51532890-744b-11e6-815f-32d2677c7afc.png">

**Comment by sensescape** [comment]
<img width="359" alt="screen shot 2016-09-06 at 5 55 38 pm" src="https://cloud.githubusercontent.com/assets/466585/18296014/2895ddc0-745b-11e6-9aa5-615b9e4d29fb.png">
http://localhost:8000/?animated=false#18/52.54468/13.41683

**Comment by nvkelso** [comment]
Is this a duplicate of https://github.com/tangrams/tron/issues/73?

**Comment by sensescape** [comment]
yes, will close this
