### ISSUE TITLE
Add sdk & eraser map icons, route line & etc

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#92]
We need generic map pins, route arrow, maybe resurrect the orange line from the underwater cables design & etc.
- layer ordering: https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L95-L150
- ux sprites: https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L512-L521
- debug sources: https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L538-L591
- layer styles: https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L955-L1098

**Comment by sensescape** [comment]
this is done:
https://github.com/tangrams/tron/commit/31204f49c3a775a2c3cbd9f945779bf1d97ec836

**Comment by sensescape** [comment]
create assets

**Comment by sensescape** [comment]
Hi! @nvkelso 
I moved over sdk and ux to globals.yaml and removed from tron.yaml
https://github.com/tangrams/tron/commit/62b3533c5836f692543838a934f059866278ae09

getting this error:
<img width="1549" alt="screen shot 2016-09-08 at 3 51 32 pm" src="https://cloud.githubusercontent.com/assets/466585/18369717/53f27dfc-75dc-11e6-83c1-2ce1b2e7de3a.png">

**Comment by nvkelso** [comment]
(We fixed this.)

**Comment by sensescape** [comment]
this is done

<img width="860" alt="screen shot 2016-09-14 at 6 28 13 pm" src="https://cloud.githubusercontent.com/assets/466585/18535437/12e9366c-7aa9-11e6-93f1-1ce3eb63008e.png">

**Comment by nvkelso** [comment]
WOW!

Can you look at badge size for station asset? The top looks clipped off.

**Comment by sensescape** [comment]
fixed:

<img width="274" alt="screen shot 2016-09-15 at 1 06 08 pm" src="https://cloud.githubusercontent.com/assets/466585/18565588/31a917ec-7b45-11e6-8c0a-36faeeeb849a.png">
