### ISSUE TITLE
Create no-labels version of Tron

### ISSUE THREAD

**Issue by sensescape** [tangrams/tron-style#94]
return buildings to original color:
https://github.com/tangrams/tron/commit/1726d4ef7cd6a5638c8204d7064bfa194781c16a
https://github.com/tangrams/tron/commit/0433f4b4741a346c9f4495a21a45404ce6073c96

**Comment by sensescape** [comment]
this is in progress:
https://github.com/tangrams/tron/commit/f45a999c676aa6d3db96601d2e13e3a16c681cfe

**Comment by sensescape** [comment]
This is mostly working now in https://github.com/tangrams/tron/commit/9defad3567a8162d121244cc8008702851336705, small about of DAT ux work left.

**Comment by nvkelso** [comment]
Fixed DAT ux work in 9548991bc5d2595b1ee3a8220c2266a44c141dd1.

There are a few townspots that don't hide at zoom 9 and 10. Once that is fixed this can be closed.
